import { nanoid } from "nanoid";

let ProductData = [
    {
        id: nanoid(),
        title: "Handmade Katana 1045 Carbon Steel With Blue Blade And Scabbard",
        price: "399",
        image: 'images/katana-1.jpg',
        inTheCart: false,
        quantity: 1,
        description: 'Unique and striking blue steel blade, full-tang battle ready japanese katana samurai sword.',
    },
    {
        id: nanoid(),
        title: "Handmade Japanese Sword 1045 Carbon Steel With Orchid Tsuba",
        price: '399',
        image: 'images/katana-2.jpg',
        inTheCart: false,
        quantity: 1,
        description: `This red katana samurai sword is a full-tang, battle-ready sword, isn't just a pretty display piece.`,
    },
    {
        id: nanoid(),
        title: "Handmade Japanese Katana T10 Carbon Steel With Blue Blade And Scabbard",
        price: '399',
        image: 'images/katana-3.jpg',
        inTheCart: false,
        quantity: 1,
        description: 'Expertly hand forged by seasoned sword smiths using proven, centuries-old technique.',
    },
    {
        id: nanoid(),
        title: "Handmade Katana Sword High Manganese Steel With Golden Blade",
        price: '399',
        image: 'images/katana-4.jpg',
        inTheCart: false,
        quantity: 1,
        description: 'High manganese steel blade, golden scabbard, dragon theme tsuba, golden cord handle with white ray-skin wrap.',
    },
    {
        id: nanoid(),
        title: "Handmade Japanese Katana Sword With Blue Blade And Silver Scabbard",
        price: '349',
        image: 'images/katana-5.jpg',
        inTheCart: false,
        quantity: 1,
        description: '1045 carbon steel blade, silver scabbard, round theme tsuba, silver cord handle with black ray-skin wrap.',
    },
    {
        id: nanoid(),
        title: "Handmade Tsushima Ghost Clan Sakai Katana Swords Cosplay Replica With Blue Blade",
        price: '349',
        image: 'images/katana-6.jpg',
        inTheCart: false,
        quantity: 1,
        description: 'Unique and striking carbon steel blade, full-tang battle ready japanese katana samurai sword.',
    },
    {
        id: nanoid(),
        title: "Handmade Katana Sword 1060 Carbon Steel With Blue Blade And Scabbard",
        price: '349',
        image: 'images/katana-7.jpg',
        inTheCart: false,
        quantity: 1,
        description: 'Unique and striking blue carbon steel blade, full-tang battle ready japanese katana samurai sword.',
    },
    {
        id: nanoid(),
        title: "Blue Lightning Blade Katana, Handmade Japanese Sword High Manganese Steel With Gray Scabbard",
        price: '349',
        image: 'images/katana-8.jpg',
        inTheCart: false,
        quantity: 1,
        description: 'Expertly hand forged by seasoned sword-smiths using proven, centuries-old techniques.',
    },
    {
        id: nanoid(),
        title: "Handmade Japanese Samurai Sword 1060 Carbon Steel With Black Scabbard",
        price: '349',
        image: 'images/katana-9.jpg',
        inTheCart: false,
        quantity: 1,
        description: 'Black dragon theme lacquered hard wood saya, premium alloy fittings, ray skin, cotton cord wrapped handle',
    },
]

export default ProductData;